---
title: Raspberry Pi にブザーを接続する
hero_image: images/banner.png
description: rpi-connect-buzzer の説明
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies:
site_areas:
steps:
  - 
    title: Raspberry Pi にブザーを接続する
